### ISSUE TITLE
Http response code 404 on 'https://connect.ubi.com/ubiservices/v2/profiles/sessions'

### ISSUE THREAD

**Issue by DevJeon1358** [danielwerg/r6api.js#19]
https://connect.ubi.com/ubiservices/v2/profiles/sessions is responding with 404 status.

**Comment by danielwerg** [comment]
change LOGIN url from "https://uplayconnect.ubi.com/ubiservices/v2/profiles/sessions" to "https://uplayconnect.ubi.com/ubiservices/v2/profiles/sessions"

**Comment by danielwerg** [comment]
I'll fix it by tomorrow

**Comment by danielwerg** [comment]
Fixed https://github.com/danielwerg/r6api.js/releases/tag/v1.1.1
