### ISSUE TITLE
Unable to figure out or use different platforms

### ISSUE THREAD

**Issue by LostAndDead** [danielwerg/r6api.js#21]
All im basically asking is instead of `uplay` for the platform what do i use to get data from other platforms

**Comment by EndBug** [comment]
The other available platforms are `xbl` (Xbox Live) and `psn` (PlayStation Network)
A note in the docs to clarify that would be useful

**Comment by LostAndDead** [comment]
Yea a note really would be useful ive been looking in the code for hours trying to find something useful, Thanks tho

**Comment by EndBug** [comment]
You're welcome ;)
