### ISSUE TITLE
Help: getting familiar with r6 api

### ISSUE THREAD

**Issue by DanielSmith1239** [danielwerg/r6api.js#23]
How do I find more possible statistics provided in the r6 api? For example, `operatorpvp_clash_sloweddown`, as you mentioned in the readme.

**Comment by danielwerg** [comment]
Sorry for late reply.

First thing you can do is go to `https://game-rainbow6.ubi.com/en-us/uplay/player-statistics/$ID` and using browser dev tools sort requests by XHR, by doing that you will get most of all possible statistics, if you want to go beyond that all you can really do is just guess statistics names afaik.

You can also try to contact ubisoft support and ask them for full list of statistics, never tried myself, doubt they can give any useful reply, but it's never hurts to try.

I'll try remember and comment here later if I can find something useful.
