### ISSUE TITLE
FetchError: invalid json response 

### ISSUE THREAD

**Issue by FiFeX** [danielwerg/r6api.js#32]
Hi, I tried to use the API and get an ID and got this error:

> FetchError: invalid json response body at https://connect.ubi.com/ubiservices/v2/profiles/sessions reason: Unexpected token < in JSON at position 0  

Example:
`let user=await r6.getId('uplay',"randomUsername");`
it does work at the official tracker (after I log in ofc).

How can I fix this?

**Comment by danielwerg** [comment]
What version you are using? Newest version using this as login `https://public-ubiservices.ubi.com/v3/profiles/sessions`, `v3` instead of `v2`.

Try updating to latest version

**Comment by FiFeX** [comment]
Oh yeah, just updated that, I'm kinda new to node and I just realized that the package.json forced me to stay at the older version.
Thanks.
