### ISSUE TITLE
Cannot find console players' stats by the userId returned by the getId method

### ISSUE THREAD

**Issue by kripi-png** [danielwerg/r6api.js#35]
What's the difference between the id and userId returned by the getId method? For uplay/pc user id and userId seems to be same, but for xbox and ps players it's not. Is there a reason for this or is it a bug?
![uplay](https://i.imgur.com/i4m5yk9.png "Uplay")
![xbox](https://i.imgur.com/L6hxe0t.png "XBox")
![ps](https://i.imgur.com/wOG1qI8.png "PS")

getStats("psn/xbl", id) method does not work with the userId but id works correctly. However, finding the profile picture (`https://ubisoft-avatars.akamaized.net/${id}/default_256_256.png`) works with the userId but not with the id.

Everything works correctly with uplay users.

**Comment by danielwerg** [comment]
I'm honestly not completely sure, never owned a console so not sure how thing work there.
But I assume this: there could be players with same `userId` but there no players with same `id`.

So I think you need to use `id` to get correct avatar.

Current docs is outdated, take a look at https://github.com/danielwerg/r6api.js/blob/typescript/README.md
