### ISSUE TITLE
Need informations with this API

### ISSUE THREAD

**Issue by YuiKozFR** [danielwerg/r6api.js#36]
Hi, I have just a little question in the API docs I didn't see for exemple (if username exists => well... )
This is my question, Actually we make a BOT Discord for report Rainbow Six player But I can't find an API that makes sure to find whether or not a player exists in the game 

(Sorry for this english, I used a translator 😬 )

**Comment by danielwerg** [comment]
You wanna make sure player played a game?
Get their id and then check if they have more than 0 xp

**Comment by YuiKozFR** [comment]
Oh nice idea but.. How i can check that, I try

`const username = args[0],
      platform = args[1];
     
    const id = await r6api.getId(platform, username).then(el => el[0].userId);
    const playerbefore = await r6api.getLevel(platform, id).then(el => el[0].userId);

    message.channel.send(username + " " + playerbefore.xp)`

But not working ".xp" How we can see xp with getLevel function ? 😞

**Comment by YuiKozFR** [comment]
Oh nice idea 👌 Thanks for this answer 😄

**Comment by YuiKozFR** [comment]
Yu I have a little problem, It's possible to check if player exists in API ? because now if I execute my command with unknow player I have one error "`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userId' of undefined`"

Or if we can set plateforme = 'all' 🤷

**Comment by danielwerg** [comment]
That's because `el[0]` in undefined
You want to do something like this:
```js
const getId = await r6api.getId(platform, username).catch(err => console.log(err));
if (!getId || !getId[0]) return console.log('user not found');
const { 0: { id } } = getId;
```
Also not r6api.js related.
