### ISSUE TITLE
Error: Stripped in prod

### ISSUE THREAD

**Issue by JoshuaTan02** [danielwerg/r6api.js#37]
I tried running the sample code and got an error.
(node:41101) UnhandledPromiseRejectionWarning: Error: Stripped in prod

**Comment by danielwerg** [comment]
Which version are you running? And can you provide code which causing this error so I can try to reproduce it

**Comment by JoshuaTan02** [comment]
Hi, I was able to get it working. i had to use the game-rainbow6.ubi.com to find the right parameters. I was just wondering how do I find operator stats?

**Comment by JoshuaTan02** [comment]
When I try running it in vscode, I am using 1.5.0 and it is not working

**Comment by JoshuaTan02** [comment]
Also, I saw your code and you are able to get stats for specific weapons. 
"weapon${type}_kills"
I was wondering what the 'type' is

**Comment by danielwerg** [comment]
> i had to use the game-rainbow6.ubi.com to find the right parameters

what parameters?

> When I try running it in vscode

What do u mean by that?

> I was wondering what the 'type' is

it's either `pvp` or `pve`

If you referring to this https://github.com/danielwerg/r6api.js#example as "sample code" then I can't reproduce the error

**Comment by JoshuaTan02** [comment]
The parameters was for something else sorry. But I did npm install and used the sample code in vs code but got an error.

**Comment by JoshuaTan02** [comment]
I tried using pvp and pve for the weapon{type}_kills but I ended up getting empty strings.

**Comment by danielwerg** [comment]
> 
> 
> I tried using pvp and pve for the weapon{type}_kills but I ended up getting an empty result.

Where do you even insert `weapon{type}_kills` to?
The whole point of this wrapper is so you don't have to deal with this kind of stuff in your app. As shown in example to get total amount of matches played you could do `stats.pvp.general.matches` same way you can get total amount of kills with AR33, for example, `stats.pvp.weapons.assault.list.find(weapon => weapon.name === 'AR33')`

**Comment by JoshuaTan02** [comment]
I understand that but I was also wanting to get a better understanding of how the api works. I tried using 'weaponpvp_kills' in the stats endpoint but got an empty result.

**Comment by danielwerg** [comment]
Apology for late reply.
But once again, I can't really help you here without seeing your code. I don't know what u mean by "using `weaponpvp_kills`".
Are you even using this module at this point? If not you can request `https://public-ubiservices.ubi.com/v1/spaces/5172a557-50b5-4665-b7db-e3f2e8c5041d/sandboxes/OSBOR_PC_LNCH_A/playerstats2/statistics?populations=0b95544b-0228-49a7-b338-6d15cfbc3d6a&statistics=weaponpvp_kills` with following headers:
```js
'Ubi-AppId': '39baebad-39e5-4552-8c25-2c9b919064e2',
'Content-Type': 'application/json; charset=UTF-8',
'Authorization': `Ubi_v1 t=${TOKEN}`
```
Response I got from in postman: https://i.imgur.com/XDkZCjP.png

If you are using this module read README again and take a look at `custom` section. It's hard to help you here when I don't understand your goal.
