### ISSUE TITLE
Error: 'TypeError: Cannot read property 'name' of undefined'

### ISSUE THREAD

**Issue by DennisDriessenLochem** [danielwerg/r6api.js#43]
Hello,

I keep getting the following error using `getRank`. 
It returns the following error `TypeError: Cannot read property 'name' of undefined`

![image](https://user-images.githubusercontent.com/39269163/97630474-f8823500-1a2f-11eb-89e6-a4deef1aac19.png)

The error only occurs using the getRank. Other functions work fine. Please help!

Code:
```
async function getR6Stats(playerName, commandName, mmr = 0){
    const channel = bot.channels.cache.get(r6Channel);
    const platform = 'uplay';
    const playerID = await r6api.getId(platform, playerName).then(el => el[0].userId);
    const data = await r6api.getRank(platform, playerID).then(el => el[0]);
};
```

**Comment by danielwerg** [comment]
Couldn't reproduce it on v1.5.0

Looks like you are running on old version and it's simply doesn't have shadow legacy object with `name`, `color` and `image` values https://i.imgur.com/BEwO1ES.png

**Comment by DennisDriessenLochem** [comment]
`package.json` says is running on v1.5.0. Any tips for fixes? Using npm.

**Comment by danielwerg** [comment]
Try uninstalling and installing it back. Even tried it on runkit it's definitely broken on your side https://runkit.com/giveaccount/5f9b36c3bffc1f001c1379f7

**Comment by DennisDriessenLochem** [comment]
Rebooting the whole server did the charm >.>
