### ISSUE TITLE
How to use Promises

### ISSUE THREAD

**Issue by OneKoin** [danielwerg/r6api.js#45]
```javascript
const R6API = require('r6api.js');
const r6api = new R6API('mail@mail.com', 'password');

const username = 'wikipedia.org', platform = 'uplay';

var r6temp = (async function(platform, username){
     const id = await r6api.getId(platform, username).then(el => el[0].userId);
     return id; 
})(platform, username);
var id = r6temp;

console.log('User Id of ${username} is ${id}');
```

this code outputs

```
[object Promise]
```

but by 
```javascript
const id = await r6api.getId(platform, username).then(el => el[0].userId);
```
this code will show me my userid
(of course only in runkit, i get "await is only valid in async function" on my console)

Can someone help me how to make my code show my userid?

**Comment by EndBug** [comment]
You need to use the Promise correctly. One way to do it is:
```js
r6api
  .getId(platform, username)
  .then(el => el[0].userId)
  .then(console.log)
```

If you've never worked with asynchronous code yet, it's better if you watch/read a couple of guides, since it's a broad subject and it would be difficult to teach you everything in this issue.

**Comment by OneKoin** [comment]
I've done that too and it gave me the same result

ok, i am using this package with discord.js.
the id shows properly only in console in asynchronous function.
But it does not show properly on discord message.
Maybe i'll review my full code again until i find why.

Thank you for your help anyway.
