### ISSUE TITLE
Issue when using Webpack

### ISSUE THREAD

**Issue by Parzival42** [danielwerg/r6api.js#52]
Hi!

I am using `r6api.js` within an electron application (I am using the [Vue CLI Plugin Electron Builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/)). However, it occurred to me that using `r6api.js` in combination with webpack fails due to:

```
TypeError: nodeFetch is not a function
    at eval (webpack:///./node_modules/r6api.js/lib/fetch.js?:10:3)
```

It seems like there is an issue using `require` together with webpack.
For example quickly changing `const nodeFetch = require('node-fetch');` to `const nodeFetch = require('node-fetch').default;` in `/lib/fetch.js` solves the issue for me. However, I didn't investigate too much if this may introduce other issues.

You can find some more infos about this problem here:
- https://github.com/node-fetch/node-fetch/issues/450?fbclid=IwAR3JKduR6WXeBQvbe_p86LGAEUyKGU1eK7LAjiPCbZWkOB3z69rmQ8Ge9nE
- https://github.com/webpack/webpack/issues/4742

Is there any chance you could make `r6api.js` webpack ready?
Thanks in advance!

**Comment by danielwerg** [comment]
Run into this issue myself the other day, using `typescript` branch myself which is works fine with webpack but obviously can't recommend you that because of breaking changes. Keep doing that you doing if it's works, will try to merge typescript branch after realese of North Star
