### ISSUE TITLE
Error: 400 Stripped in prod

### ISSUE THREAD

**Issue by PixelNinja132** [danielwerg/r6api.js#62]
Hey,

I keep trying to use functions such as getProgression and getRanks but they all say "Error: 400 stripped in prod". Does anyone know why this is happening?

Thanks.

**Comment by PixelNinja132** [comment]
Notes: I'm using PSN usernames in an ASYNC function with await.

**Comment by danielwerg** [comment]
You doing something wrong in your end, need to see your code tell what it is. My guess is you are using wrong type of id.

**Comment by PixelNinja132** [comment]
Ah, my bad, sorry. I was trying to use the PSN name instead of first fetching the ID.

Is there a way to get all players in a match by match ID? Thanks

**Comment by danielwerg** [comment]
> Is there a way to get all players in a match by match ID?

Not that I know of

**Comment by PixelNinja132** [comment]
Ah k, tysm!
