### ISSUE TITLE
R6API class is under double default export

### ISSUE THREAD

**Issue by BadCoder1337** [danielwerg/r6api.js#67]
I'm using r6api.js as ES Module
```
PS C:\Users\NO_RUSSIAN_SYMBOLS\Projects\temp> node
Welcome to Node.js v16.3.0.
Type ".help" for more information.
> import("r6api.js").then(m => r6api = m)
Promise { <pending> }
> r6api.default.default
[class R6API]
```

That prevents proper usage with TypeScript. Declarations have correct default export. ES6 usage from README works only with transpiler.

**Comment by danielwerg** [comment]
Could you provide an example from an actual project? I haven't had any issue in my ts projects. ESM stuff is confusing :/

**Comment by BadCoder1337** [comment]
Just need two files
- Create `package.json` like this to switch node to native ES Modules by default

```json
{
    "type": "module",
    "dependencies": {
        "r6api.js": "2.1.0"
    }
}
```
- `yarn install`
- Create `test.js` like this
```js
import R6API, { constants, typings, utils/* , fetch */ } from "r6api.js" // error for fetch import
console.log("R6API", R6API.toString(), R6API.default?.toString())
console.log("constants", constants.toString())
console.log("typings", typings.toString())
console.log("utils", utils.toString())
// console.log("fetch", fetch.toString())
```
- `node test.js`

First string will be `R6API [object Object] class R6API { ... }`. R6API is not a class. R6API is already a default import, so R6API.default type is any causing TS error.
