### ISSUE TITLE
Crystal Guard season data

### ISSUE THREAD

**Issue by PoloLacoste** [danielwerg/r6api.js#72]
Hi,
The last season, Crystal Guard is out right now. 
It would be nice to add the lastest data for this season.

Thanks !

**Comment by PoloLacoste** [comment]
Hi,
The last season, Crystal Guard is out right now. 
It would be nice to add the lastest data for this season.

Thanks !

**Comment by danielwerg** [comment]
some progress :)

https://github.com/danielwerg/r6api.js/commit/faf0b1b623f513e3724ac1980f82ccc58e7af01a

**Comment by danielwerg** [comment]
https://github.com/danielwerg/r6api.js/releases/tag/v3.0.0
