### ISSUE TITLE
Please stop changing the banner URLs

### ISSUE THREAD

**Issue by PixelNinja132** [danielwerg/r6api.js#76]
My program stops working each season when you change the banner URLs. I feel like it would be more effective if you made a new folder for the changes like with the versions except leaving the old ones in a folder of the previous version. This way, when updating, you can just change the folder version in the URL to get the latest designs without having to change it the day of updates.

**Comment by danielwerg** [comment]
I'm assuming you talking about rank and operator icons, right?

> My program stops working each season when you change the banner URLs

Then there something wrong with your code. It was meant to be used in small projects (ex: discord bot), for bigger projects I don't recommend using it, you should have your own logic. Besides for operator icons you can use svg, if you need svg version of rank icons I can send them to you, let me know.

iirc, last time I had to change it was when Ubisoft removed `Diamond` and added `Diamond 1`, `Diamond 2` and `Diamond 3`, which would result in wrong rank icon with current logic, so you would have to update r6api.js regardless.
