### ISSUE TITLE
Unable to get the regions informations from getRanks

### ISSUE THREAD

**Issue by Kynetick** [danielwerg/r6api.js#84]
Hey !
So im now trying for hours to get the seasonal KD out of `getRanks`, but this always return this :
![Capture d’écran (760)](https://user-images.githubusercontent.com/65234150/161126896-119a4792-569d-453f-94f7-3ca3f3e5c447.png)
and always return that `regions` is undefined.

Did i miss something ? Or mby some parts are not working anymore ?

**Comment by danielwerg** [comment]
How come? Even in your screenshot it's **not** `undefined`. Need to see a code which returns undefined to be sure, but it looks like a problem on your side.

**Comment by Kynetick** [comment]
Here it is :
![Capture d’écran (766)](https://user-images.githubusercontent.com/65234150/161251161-4bd51e99-bca4-4826-bdab-17d008f96695.png)
And here is the code im running with. I tried several things but it always fails at the same point, this code was my last attempt :
```javascript
const { 0: rank} = await r6api.getRanks(platform, player.id, {regionIds: 'emea', boardIds: 'pvp_ranked' })
const { seasons: { "-1": { regions: { emea: { boards: { pvp_ranked }} } } } } = rank;
console.log(rank);
----------------------------------
//.addFields comes from discordjs lib
.addFields(
        { name: 'K/D', value: `${/* kd will be displayed here */}`, inline: true },
)

**Comment by danielwerg** [comment]
Not a package related issue.

---

There will never be season with array index of `-1`, change it to:
```ts
const { 0: rank } = await r6api.getRanks(
  platform, id, { regionIds: 'emea', boardIds: 'pvp_ranked' }
);
if (!rank) return;
const { seasons: { 25: { regions: { emea: { boards: { pvp_ranked }} } } } } = rank;
console.log(pvp_ranked);
```
Or even better to:
```ts
const rank = await r6api.getRanks(
  platform, id, { regionIds: 'emea', boardIds: 'pvp_ranked' }
).catch(console.error);
if (!rank || !rank.length) return; // handle error
const latestSeason = Object.values(rank[0]?.seasons || {}).slice(-1)[0];
if (!latestSeason) return; // handle error
const { regions: { emea: { boards: { pvp_ranked } } } } = latestSeason;
console.log(pvp_ranked);
```
