### ISSUE TITLE
Error: 401 Invalid credentials

### ISSUE THREAD

**Issue by LillieH001** [danielwerg/r6api.js#86]
Hello, no matter what I seem to do I always get invalid creditidentals for this api, I provided my basic code below, I did put in my actual ubisoft account info in the actual code but in the example I removed it.

```const R6API = require('r6api.js').default;
const r6api = new R6API("email", "password");
const username = 'Daniel.Nt';
const platform = 'uplay';
const player = await r6api.findByUsername(platform, username);
const stats = await r6api.getStats(platform, player.id);
return stats.pvp.general.matches;

**Comment by danielwerg** [comment]
What version are you on?

In the latest versions R6API constructor only accepts one parameter - object. See: https://github.com/danielwerg/r6api.js#constructor

Replace:
```js
const r6api = new R6API("email", "password");
```
With:
```js
const r6api = new R6API({ email: "EMAILGOESHERE", password: "PASSWORDGOESHERE" });
```

> Note for myself: Add issue templates, allow only bug reports and feature requests?, redirect rest to discord (also github discussions or just make another issue template for help related issues)?

**Comment by LillieH001** [comment]
Oh, thank you, I thought the object was just because of the dotenv, my bad.
