### ISSUE TITLE
Patch version request

### ISSUE THREAD

**Issue by EndBug** [danielwerg/r6api.js#87]
Hey @danielwerg would you be able to publish the fix I've just pushed in 71ea80181505d5adaac524e793c255f33f933cb3?
We should also think of adding a way for the package to build if it gets installed from GitHub, for example with a `prepare` script

**Comment by danielwerg** [comment]
Won't be able until monday/tuesday, sorry :(

**Comment by danielwerg** [comment]
https://github.com/danielwerg/r6api.js/releases/tag/v4.2.1

**Comment by EndBug** [comment]
Thanks ❤️
