### ISSUE TITLE
Package can't be installed from GitHub

### ISSUE THREAD

**Issue by EndBug** [danielwerg/r6api.js#88]
As of now, if the package gets installed from GitHub it won't be compiled, and so it will not be usable.
A solution to this would be adding a [`prepare`](https://docs.npmjs.com/cli/v8/using-npm/scripts#prepare-and-prepublish) script that checks whether the `dist` folder is already there, otherwise runs the `build` script.
A working example is `dbots.js`: https://github.com/dbots-pkg/dbots.js/blob/adb1219db00a1d11daece7e2309834fa33a3e963/package.json#L18

What do you think?

**Comment by danielwerg** [comment]
As long as it doesn't interfere with npm package — I'm for it.
